name: Build and Test (codeforces)

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      - 'codeforces/*'

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Dependencies
      uses: actions/cache@v1.2.0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache Tests
      uses: actions/cache@v1.2.0
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-testcache

    - name: Test
      run: go test -v ./codeforces
      env:
        CODEFORCES_USERNAME: cp-tools
        CODEFORCES_PASSWORD: ${{ secrets.CODEFORCES_PASSWORD }}

