name: Build and Test (codeforces)

on:
  push:
    tags-ignore: ['*']
    paths: ['codeforces/*']

  pull_request:
    paths: ['codeforces/*']

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest 

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout Project
        uses: actions/checkout@v2
      
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Set Public Test Mode
        if: github.event_name == 'pull_request'
        run: echo "PUBLIC_TESTS_ONLY=" >> $GITHUB_ENV 

      - name: Run Test
        run: go test -v -coverprofile=c.out ./codeforces
        env:
          BROWSER_HEADLESS:
          BROWSER_BINARY: google-chrome

          CODEFORCES_USERNAME: cp-tools
          CODEFORCES_PASSWORD: ${{ secrets.CODEFORCES_PASSWORD }}


      - name: Upload Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: c.out

